"""The release metadata makes claims too, and nothing was checking them.

`.zenodo.json` is the description that ends up on the permanent deposit, so it outlives every
other copy of these numbers. It had drifted: it still said graph indexes "collapse below 45%
recall@10" long after the README was corrected to 50% — `yi-128-ip` at M=96 reaches 45.38% —
and still described acceptance rising "by an order of magnitude" when the measured range is
3.3x to 19.6x.

The README's numbers were guarded; this file's were not. Now they are.
"""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
ZENODO = ROOT / '.zenodo.json'
CITATION = ROOT / 'CITATION.cff'

#: The paper's headline configuration, which the description's figures are quoted at.
HEADLINE_M = 48


@pytest.fixture(scope='module')
def description() -> str:
    """The Zenodo description with its HTML stripped, so claims can be matched as prose."""
    raw = json.loads(ZENODO.read_text())['description']
    return re.sub(r'<[^>]+>', ' ', raw)


@pytest.fixture(scope='module')
def table1() -> list[dict[str, str]]:
    with (ROOT / 'results' / 'table1_degree.csv').open(newline='') as handle:
        return list(csv.DictReader(handle))


def _cell(rows: list[dict[str, str]], dataset: str, normalization: str, column: str, m: int = HEADLINE_M) -> float:
    for row in rows:
        if row['dataset_name'] == dataset and row['m'] == str(m) and row['normalization'] == normalization:
            return float(row[column])
    msg = f'no row for {dataset} M={m} {normalization}'
    raise AssertionError(msg)


def test_the_recall_ceiling_it_quotes_covers_every_configuration(description, table1):
    """Unqualified in the description, so it must hold across all of Table 1, not just M=48."""
    match = re.search(r'collapse below (\d+)% recall@10', description)
    assert match, 'the description no longer states a recall ceiling'
    ceiling = int(match.group(1))

    worst = max(float(r['recall_avg']) for r in table1 if r['normalization'] == 'none') * 100
    assert worst < ceiling, f'raw recall reaches {worst:.2f}%, so "below {ceiling}%" is false'


def test_the_acceptance_figures_are_the_measured_ones(description, table1):
    for dataset, raw, transformed in (('yi-128-ip', 1.5, 13.4), ('llama-128-ip', 1.1, 22.0)):
        assert round(_cell(table1, dataset, 'none', 'accepted_candidates_avg'), 1) == raw
        assert round(_cell(table1, dataset, 'bachrach', 'accepted_candidates_avg'), 1) == transformed
        assert f'{raw} candidates to {transformed}' in description or f'from {raw} to {transformed}' in description


def test_it_does_not_reclaim_an_order_of_magnitude(description, table1):
    """Measured across Table 1 the ratio runs 3.3x to 19.6x, so the phrase overstates the floor."""
    ratios = [
        _cell(table1, dataset, 'bachrach', 'accepted_candidates_avg', m)
        / _cell(table1, dataset, 'none', 'accepted_candidates_avg', m)
        for dataset in ('yi-128-ip', 'llama-128-ip')
        for m in (4, 16, 48, 96)
    ]
    assert min(ratios) < 10, 'if the smallest ratio is now >=10x, this guard can be relaxed'
    assert 'order of magnitude' not in description


def test_the_candidate_pool_it_quotes_is_the_one_that_was_run(description, table1):
    assert '500-candidate pool' in description
    assert {r['ef_construction'] for r in table1} == {'500'}


def test_the_deposit_does_not_advertise_files_the_repository_lacks(description):
    """It promised serialized indexes; there are none, and none are generated by any entry point."""
    if 'serialized index' in description:
        assert (ROOT / 'indexes').is_dir(), 'the description promises serialized indexes that do not exist'


def test_the_doi_is_stated_identically_everywhere():
    doi = '10.1145/3799682.3839984'
    assert doi in json.loads(ZENODO.read_text())['related_identifiers'][0]['identifier']
    assert doi in CITATION.read_text()
    assert doi in (ROOT / 'README.md').read_text()
